"""Initial migration

Revision ID: 9e9891b90d08
Revises:
Create Date: 2026-09-24 19:30:49.402016

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "9e9891b90d08"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.String(length=50), nullable=False),
        sa.Column("spec", sqlite.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("node_id", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.node_id"]),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index("ix_jobs_created_at", "jobs", ["created_at"], unique=False)
    op.create_index("ix_jobs_node_id", "jobs", ["node_id"], unique=False)
    op.create_index("ix_jobs_status", "jobs", ["status"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("node_id", sa.String(length=50), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("gpus", sqlite.JSON(), nullable=False),
        sa.Column("cpus", sa.Integer(), nullable=False),
        sa.Column("memory_gb", sa.Integer(), nullable=False),
        sa.Column("os", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ONLINE", "OFFLINE", name="node_status"),
            nullable=False,
        ),
        sa.Column("last_heartbeat", sa.DateTime(), nullable=False),
        sa.Column("current_job_id", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["current_job_id"], ["jobs.job_id"]),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.create_index(
        "ix_nodes_last_heartbeat", "nodes", ["last_heartbeat"], unique=False
    )
    op.create_index("ix_nodes_status", "nodes", ["status"], unique=False)
    op.create_table(
        "cpu_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("cpu_percent", sa.Integer(), nullable=False),
        sa.Column("memory_percent", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cpu_metrics_job_id"), "cpu_metrics", ["job_id"], unique=False
    )
    op.create_index(
        "ix_cpu_metrics_job_timestamp",
        "cpu_metrics",
        ["job_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "gpu_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("gpu_index", sa.Integer(), nullable=False),
        sa.Column("memory_used_mb", sa.Integer(), nullable=False),
        sa.Column("memory_total_mb", sa.Integer(), nullable=False),
        sa.Column("utilization_percent", sa.Integer(), nullable=False),
        sa.Column("temperature_c", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gpu_metrics_job_id"), "gpu_metrics", ["job_id"], unique=False
    )
    op.create_index(
        "ix_gpu_metrics_job_timestamp",
        "gpu_metrics",
        ["job_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "log_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("line", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_entries_job_id"), "log_entries", ["job_id"], unique=False
    )
    op.create_index(
        "ix_log_entries_job_timestamp",
        "log_entries",
        ["job_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_log_entries_job_timestamp", table_name="log_entries")
    op.drop_index(op.f("ix_log_entries_job_id"), table_name="log_entries")
    op.drop_table("log_entries")
    op.drop_index("ix_gpu_metrics_job_timestamp", table_name="gpu_metrics")
    op.drop_index(op.f("ix_gpu_metrics_job_id"), table_name="gpu_metrics")
    op.drop_table("gpu_metrics")
    op.drop_index("ix_cpu_metrics_job_timestamp", table_name="cpu_metrics")
    op.drop_index(op.f("ix_cpu_metrics_job_id"), table_name="cpu_metrics")
    op.drop_table("cpu_metrics")
    op.drop_index("ix_nodes_status", table_name="nodes")
    op.drop_index("ix_nodes_last_heartbeat", table_name="nodes")
    op.drop_table("nodes")
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_index("ix_jobs_node_id", table_name="jobs")
    op.drop_index("ix_jobs_created_at", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
